### ISSUE TITLE
[Mac] Error 'archive.h' file not found (build seeks version that doesn't exist)

### ISSUE THREAD

**Issue by drscotthawley** [artandlogic/vibrary#2]
It seems to be looking for a version of libarchive (3.4.0) that doesn't exist on my system:

from build.log: 

CompileC build/Vibrary.build/Release/Vibrary\ -\ App.build/Objects-normal/x86_64/PaxArchive.o /Users/shawley/github/vibrary/Source/PaxArchive.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/shawley/github/vibrary/Builds/MacOSX
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.12 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++1z -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O3 -flto -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wnon-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -D_NDEBUG=1 -DNDEBUG=1 -DJUCER_XCODE_MAC_F6D2F4CF=1 -DJUCE_APP_VERSION=autolist1213121412131215-690558576-690558575 -DJUCE_APP_VERSION_HEX=0x0 -DJucePlugin_Build_VST=0 -DJucePlugin_Build_VST3=0 -DJucePlugin_Build_AU=0 -DJucePlugin_Build_AUv3=0 -DJucePlugin_Build_RTAS=0 -DJucePlugin_Build_AAX=0 -DJucePlugin_Build_Standalone=0 -DJucePlugin_Build_Unity=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -fvisibility=hidden -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -I/Users/shawley/github/vibrary/Builds/MacOSX/build/Release/include -I../../JuceLibraryCode -I/Users/shawley/JUCE/modules -I/Users/shawley/github/vibrary/Builds/MacOSX/build/Vibrary.build/Release/Vibrary\ -\ App.build/DerivedSources-normal/x86_64 -I/Users/shawley/github/vibrary/Builds/MacOSX/build/Vibrary.build/Release/Vibrary\ -\ App.build/DerivedSources/x86_64 -I/Users/shawley/github/vibrary/Builds/MacOSX/build/Vibrary.build/Release/Vibrary\ -\ App.build/DerivedSources -Wreorder -F/Users/shawley/github/vibrary/Builds/MacOSX/build/Release -I../../3rdParty/tensorflow/dist/include/protobuf/src -I../../3rdParty/tensorflow/dist/include/tensorflow/eigen -I../../3rdParty/tensorflow/dist/include/tensorflow/bazel-genfiles -I../../3rdParty/tensorflow/dist/include/tensorflow -I../../3rdParty/tensorflow/dist/include -I../../3rdParty/cnpy/dist/include -I../../3rdParty/sqlite/src -I/usr/local/Cellar/libssh/0.9.3/include -I/usr/local/Cellar/libarchive/3.4.0/include -MMD -MT dependencies -MF /Users/shawley/github/vibrary/Builds/MacOSX/build/Vibrary.build/Release/Vibrary\ -\ App.build/Objects-normal/x86_64/PaxArchive.d --serialize-diagnostics /Users/shawley/github/vibrary/Builds/MacOSX/build/Vibrary.build/Release/Vibrary\ -\ App.build/Objects-normal/x86_64/PaxArchive.dia -c /Users/shawley/github/vibrary/Source/PaxArchive.cpp -o /Users/shawley/github/vibrary/Builds/MacOSX/build/Vibrary.build/Release/Vibrary\ -\ App.build/Objects-normal/x86_64/PaxArchive.o
In file included from /Users/shawley/github/vibrary/Source/PaxArchive.cpp:30:
/Users/shawley/github/vibrary/Source/PaxArchive.h:26:10: fatal error: 'archive.h' file not found
#include <archive.h> // Using libarchive

It seems to be looking for a version of libarchive that doesn't exist:

```bash
$ ls /usr/local/Cellar/libarchive/3.4.0/include
ls: /usr/local/Cellar/libarchive/3.4.0/include: No such file or directory
```

Instead I've got version 3.4.2_1 on my system.  But there's a symbolic link system in homebrew anyway, whereby you don't have to include based on a specific version.  Should we not be including from `/usr/local/opt/libarchive/include`?

I tried running

```
export LDFLAGS="-L/usr/local/opt/libarchive/lib"
export CPPFLAGS="-I/usr/local/opt/libarchive/include"

```
before running `MacBuildScript.sh`, but it doesn't seem to have 'included' these changes. 

One possible fix might be to instruct the user to install the specific versions that seem to be hard-coded into the build somehow. Something like...

```bash
$ brew tap homebrew/cask-versions
$ brew install libssh@0.9.3 libarchive@3.4.0
```
....but that doesn't seem to work because brew doesn't recognize those versions.  ?

**Comment by drscotthawley** [comment]
I also tried going in and manually edited the `project.pbxproj` file to correct the `-I` include directives, pointing them to `/usr/local/opt/` instead, but my changes got overwritten when running the `BuildMac.sh` file.

**Comment by drscotthawley** [comment]
Ok, the place to make the edits is in the `Vibrary.jucer` file.  Removed references to specific versions in favor of 'generic' libssh and libarchive.      I'll post my jucer file to my fork:
https://github.com/drscotthawley/vibrary/blob/master/Vibrary.jucer, and can make a Pull Request
 (although the `.jucer` file still has some absolute paths in it, e.g. `/Users/shawley/...`  I find that strange.)

With these changes, I get the `** BUILD SUCCEEDED **` at the end.

**Comment by jbagley** [comment]
The include paths need to be set in the jucer file's export settings. Otherwise, when the project is exported from Projucer or Introjucer it will lose your changes.

**Comment by jbagley** [comment]
Those paths look good to me. I didn't find them somehow.

**Comment by jbagley** [comment]
Merged changes after making some fixes in the jucer file (some of which started on my dev machine).
